# Generated by Django 4.2 on 2024-01-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_value',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
